//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class StudentDTO : object
    {
        
        private long IdEstudianteField;
        
        private string NombreField;
        
        private System.Collections.Generic.List<StudentService.ProgramDTO> ProgramaField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<StudentService.ProgramDTO> Programa
        {
            get
            {
                return this.ProgramaField;
            }
            set
            {
                this.ProgramaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class ProgramDTO : object
    {
        
        private int CreditosField;
        
        private int DuracionEnDiasField;
        
        private long IdProfesorField;
        
        private long IdProgramaField;
        
        private string NombreField;
        
        private StudentService.TeacherDTO ProfesorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creditos
        {
            get
            {
                return this.CreditosField;
            }
            set
            {
                this.CreditosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DuracionEnDias
        {
            get
            {
                return this.DuracionEnDiasField;
            }
            set
            {
                this.DuracionEnDiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdPrograma
        {
            get
            {
                return this.IdProgramaField;
            }
            set
            {
                this.IdProgramaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentService.TeacherDTO Profesor
        {
            get
            {
                return this.ProfesorField;
            }
            set
            {
                this.ProfesorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class TeacherDTO : object
    {
        
        private long IdProfesorField;
        
        private string NombreField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentRequest", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp.Models")]
    public partial class StudentRequest : object
    {
        
        private long IdEstudianteField;
        
        private string NombreField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentAssociationRequest", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp.Models")]
    public partial class StudentAssociationRequest : object
    {
        
        private long IdEstudianteField;
        
        private long IdProgramField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdEstudiante
        {
            get
            {
                return this.IdEstudianteField;
            }
            set
            {
                this.IdEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProgram
        {
            get
            {
                return this.IdProgramField;
            }
            set
            {
                this.IdProgramField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudent")]
    public interface IStudent
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudent", ReplyAction="http://tempuri.org/IStudent/GetStudentResponse")]
        StudentService.GetStudentResponse GetStudent(StudentService.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudent", ReplyAction="http://tempuri.org/IStudent/GetStudentResponse")]
        System.Threading.Tasks.Task<StudentService.GetStudentResponse> GetStudentAsync(StudentService.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentId", ReplyAction="http://tempuri.org/IStudent/GetStudentIdResponse")]
        StudentService.GetStudentIdResponse GetStudentId(StudentService.GetStudentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentId", ReplyAction="http://tempuri.org/IStudent/GetStudentIdResponse")]
        System.Threading.Tasks.Task<StudentService.GetStudentIdResponse> GetStudentIdAsync(StudentService.GetStudentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/NewStudent", ReplyAction="http://tempuri.org/IStudent/NewStudentResponse")]
        StudentService.NewStudentResponse NewStudent(StudentService.NewStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/NewStudent", ReplyAction="http://tempuri.org/IStudent/NewStudentResponse")]
        System.Threading.Tasks.Task<StudentService.NewStudentResponse> NewStudentAsync(StudentService.NewStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/EnrollProgram", ReplyAction="http://tempuri.org/IStudent/EnrollProgramResponse")]
        StudentService.EnrollProgramResponse EnrollProgram(StudentService.EnrollProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/EnrollProgram", ReplyAction="http://tempuri.org/IStudent/EnrollProgramResponse")]
        System.Threading.Tasks.Task<StudentService.EnrollProgramResponse> EnrollProgramAsync(StudentService.EnrollProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentxPrograms", ReplyAction="http://tempuri.org/IStudent/GetStudentxProgramsResponse")]
        StudentService.GetStudentxProgramsResponse GetStudentxPrograms(StudentService.GetStudentxProgramsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentxPrograms", ReplyAction="http://tempuri.org/IStudent/GetStudentxProgramsResponse")]
        System.Threading.Tasks.Task<StudentService.GetStudentxProgramsResponse> GetStudentxProgramsAsync(StudentService.GetStudentxProgramsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdateStudent", ReplyAction="http://tempuri.org/IStudent/UpdateStudentResponse")]
        StudentService.UpdateStudentResponse UpdateStudent(StudentService.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/UpdateStudent", ReplyAction="http://tempuri.org/IStudent/UpdateStudentResponse")]
        System.Threading.Tasks.Task<StudentService.UpdateStudentResponse> UpdateStudentAsync(StudentService.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/DeleteStudent", ReplyAction="http://tempuri.org/IStudent/DeleteStudentResponse")]
        StudentService.DeleteStudentResponse DeleteStudent(StudentService.DeleteStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/DeleteStudent", ReplyAction="http://tempuri.org/IStudent/DeleteStudentResponse")]
        System.Threading.Tasks.Task<StudentService.DeleteStudentResponse> DeleteStudentAsync(StudentService.DeleteStudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool conProgramas;
        
        public GetStudentRequest()
        {
        }
        
        public GetStudentRequest(bool conProgramas)
        {
            this.conProgramas = conProgramas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<StudentService.StudentDTO> GetStudentResult;
        
        public GetStudentResponse()
        {
        }
        
        public GetStudentResponse(System.Collections.Generic.List<StudentService.StudentDTO> GetStudentResult)
        {
            this.GetStudentResult = GetStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool conProgramas;
        
        public GetStudentIdRequest()
        {
        }
        
        public GetStudentIdRequest(long id, bool conProgramas)
        {
            this.id = id;
            this.conProgramas = conProgramas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.StudentDTO GetStudentIdResult;
        
        public GetStudentIdResponse()
        {
        }
        
        public GetStudentIdResponse(StudentService.StudentDTO GetStudentIdResult)
        {
            this.GetStudentIdResult = GetStudentIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewStudentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.StudentRequest student;
        
        public NewStudentRequest()
        {
        }
        
        public NewStudentRequest(StudentService.StudentRequest student)
        {
            this.student = student;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NewStudentResult;
        
        public NewStudentResponse()
        {
        }
        
        public NewStudentResponse(string NewStudentResult)
        {
            this.NewStudentResult = NewStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollProgram", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnrollProgramRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.StudentAssociationRequest studentAssociation;
        
        public EnrollProgramRequest()
        {
        }
        
        public EnrollProgramRequest(StudentService.StudentAssociationRequest studentAssociation)
        {
            this.studentAssociation = studentAssociation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EnrollProgramResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EnrollProgramResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EnrollProgramResult;
        
        public EnrollProgramResponse()
        {
        }
        
        public EnrollProgramResponse(string EnrollProgramResult)
        {
            this.EnrollProgramResult = EnrollProgramResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentxPrograms", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentxProgramsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long Id;
        
        public GetStudentxProgramsRequest()
        {
        }
        
        public GetStudentxProgramsRequest(long Id)
        {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentxProgramsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentxProgramsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<StudentService.StudentDTO> GetStudentxProgramsResult;
        
        public GetStudentxProgramsResponse()
        {
        }
        
        public GetStudentxProgramsResponse(System.Collections.Generic.List<StudentService.StudentDTO> GetStudentxProgramsResult)
        {
            this.GetStudentxProgramsResult = GetStudentxProgramsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public StudentService.StudentRequest student;
        
        public UpdateStudentRequest()
        {
        }
        
        public UpdateStudentRequest(StudentService.StudentRequest student)
        {
            this.student = student;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateStudentResult;
        
        public UpdateStudentResponse()
        {
        }
        
        public UpdateStudentResponse(string UpdateStudentResult)
        {
            this.UpdateStudentResult = UpdateStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long id;
        
        public DeleteStudentRequest()
        {
        }
        
        public DeleteStudentRequest(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteStudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeleteStudentResult;
        
        public DeleteStudentResponse()
        {
        }
        
        public DeleteStudentResponse(string DeleteStudentResult)
        {
            this.DeleteStudentResult = DeleteStudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IStudentChannel : StudentService.IStudent, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class StudentClient : System.ServiceModel.ClientBase<StudentService.IStudent>, StudentService.IStudent
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StudentClient() : 
                base(StudentClient.GetDefaultBinding(), StudentClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStudent.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), StudentClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StudentClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public StudentService.GetStudentResponse GetStudent(StudentService.GetStudentRequest request)
        {
            return base.Channel.GetStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetStudentResponse> GetStudentAsync(StudentService.GetStudentRequest request)
        {
            return base.Channel.GetStudentAsync(request);
        }
        
        public StudentService.GetStudentIdResponse GetStudentId(StudentService.GetStudentIdRequest request)
        {
            return base.Channel.GetStudentId(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetStudentIdResponse> GetStudentIdAsync(StudentService.GetStudentIdRequest request)
        {
            return base.Channel.GetStudentIdAsync(request);
        }
        
        public StudentService.NewStudentResponse NewStudent(StudentService.NewStudentRequest request)
        {
            return base.Channel.NewStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.NewStudentResponse> NewStudentAsync(StudentService.NewStudentRequest request)
        {
            return base.Channel.NewStudentAsync(request);
        }
        
        public StudentService.EnrollProgramResponse EnrollProgram(StudentService.EnrollProgramRequest request)
        {
            return base.Channel.EnrollProgram(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.EnrollProgramResponse> EnrollProgramAsync(StudentService.EnrollProgramRequest request)
        {
            return base.Channel.EnrollProgramAsync(request);
        }
        
        public StudentService.GetStudentxProgramsResponse GetStudentxPrograms(StudentService.GetStudentxProgramsRequest request)
        {
            return base.Channel.GetStudentxPrograms(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.GetStudentxProgramsResponse> GetStudentxProgramsAsync(StudentService.GetStudentxProgramsRequest request)
        {
            return base.Channel.GetStudentxProgramsAsync(request);
        }
        
        public StudentService.UpdateStudentResponse UpdateStudent(StudentService.UpdateStudentRequest request)
        {
            return base.Channel.UpdateStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.UpdateStudentResponse> UpdateStudentAsync(StudentService.UpdateStudentRequest request)
        {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        public StudentService.DeleteStudentResponse DeleteStudent(StudentService.DeleteStudentRequest request)
        {
            return base.Channel.DeleteStudent(request);
        }
        
        public System.Threading.Tasks.Task<StudentService.DeleteStudentResponse> DeleteStudentAsync(StudentService.DeleteStudentRequest request)
        {
            return base.Channel.DeleteStudentAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudent))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudent))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50410/Student.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StudentClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStudent);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StudentClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStudent);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStudent,
        }
    }
}
