//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class TeacherDTO : object
    {
        
        private long IdProfesorField;
        
        private string NombreField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherRequest", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp.Models")]
    public partial class TeacherRequest : object
    {
        
        private string NombreField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeacherService.ITeacher")]
    public interface ITeacher
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacher/GetTeacher", ReplyAction="http://tempuri.org/ITeacher/GetTeacherResponse")]
        System.Threading.Tasks.Task<TeacherService.GetTeacherResponse> GetTeacherAsync(TeacherService.GetTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacher/GetTeacherId", ReplyAction="http://tempuri.org/ITeacher/GetTeacherIdResponse")]
        System.Threading.Tasks.Task<TeacherService.GetTeacherIdResponse> GetTeacherIdAsync(TeacherService.GetTeacherIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacher/NewTeacher", ReplyAction="http://tempuri.org/ITeacher/NewTeacherResponse")]
        System.Threading.Tasks.Task<TeacherService.NewTeacherResponse> NewTeacherAsync(TeacherService.NewTeacherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherRequest
    {
        
        public GetTeacherRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<TeacherService.TeacherDTO> GetTeacherResult;
        
        public GetTeacherResponse()
        {
        }
        
        public GetTeacherResponse(System.Collections.Generic.List<TeacherService.TeacherDTO> GetTeacherResult)
        {
            this.GetTeacherResult = GetTeacherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacherId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long id;
        
        public GetTeacherIdRequest()
        {
        }
        
        public GetTeacherIdRequest(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacherIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeacherService.TeacherDTO GetTeacherIdResult;
        
        public GetTeacherIdResponse()
        {
        }
        
        public GetTeacherIdResponse(TeacherService.TeacherDTO GetTeacherIdResult)
        {
            this.GetTeacherIdResult = GetTeacherIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewTeacherRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TeacherService.TeacherRequest student;
        
        public NewTeacherRequest()
        {
        }
        
        public NewTeacherRequest(TeacherService.TeacherRequest student)
        {
            this.student = student;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewTeacherResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NewTeacherResult;
        
        public NewTeacherResponse()
        {
        }
        
        public NewTeacherResponse(string NewTeacherResult)
        {
            this.NewTeacherResult = NewTeacherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ITeacherChannel : TeacherService.ITeacher, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TeacherClient : System.ServiceModel.ClientBase<TeacherService.ITeacher>, TeacherService.ITeacher
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TeacherClient() : 
                base(TeacherClient.GetDefaultBinding(), TeacherClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITeacher.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeacherClient(EndpointConfiguration endpointConfiguration) : 
                base(TeacherClient.GetBindingForEndpoint(endpointConfiguration), TeacherClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeacherClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TeacherClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeacherClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TeacherClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeacherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TeacherService.GetTeacherResponse> GetTeacherAsync(TeacherService.GetTeacherRequest request)
        {
            return base.Channel.GetTeacherAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeacherService.GetTeacherIdResponse> GetTeacherIdAsync(TeacherService.GetTeacherIdRequest request)
        {
            return base.Channel.GetTeacherIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TeacherService.NewTeacherResponse> NewTeacherAsync(TeacherService.NewTeacherRequest request)
        {
            return base.Channel.NewTeacherAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITeacher))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITeacher))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50410/Teacher.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TeacherClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITeacher);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TeacherClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITeacher);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITeacher,
        }
    }
}
