//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class ProgramDTO : object
    {
        
        private int CreditosField;
        
        private int DuracionEnDiasField;
        
        private long IdProfesorField;
        
        private long IdProgramaField;
        
        private string NombreField;
        
        private ProgramService.TeacherDTO ProfesorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creditos
        {
            get
            {
                return this.CreditosField;
            }
            set
            {
                this.CreditosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DuracionEnDias
        {
            get
            {
                return this.DuracionEnDiasField;
            }
            set
            {
                this.DuracionEnDiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdPrograma
        {
            get
            {
                return this.IdProgramaField;
            }
            set
            {
                this.IdProgramaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProgramService.TeacherDTO Profesor
        {
            get
            {
                return this.ProfesorField;
            }
            set
            {
                this.ProfesorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherDTO", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp")]
    public partial class TeacherDTO : object
    {
        
        private long IdProfesorField;
        
        private string NombreField;
        
        private long TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramRequest", Namespace="http://schemas.datacontract.org/2004/07/RegisterSubject.Imp.Models")]
    public partial class ProgramRequest : object
    {
        
        private int CreditosField;
        
        private int DuracionEnDiásField;
        
        private long IdProfesorField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creditos
        {
            get
            {
                return this.CreditosField;
            }
            set
            {
                this.CreditosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DuracionEnDiás
        {
            get
            {
                return this.DuracionEnDiásField;
            }
            set
            {
                this.DuracionEnDiásField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdProfesor
        {
            get
            {
                return this.IdProfesorField;
            }
            set
            {
                this.IdProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramService.IProgram")]
    public interface IProgram
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgram", ReplyAction="http://tempuri.org/IProgram/GetProgramResponse")]
        ProgramService.GetProgramResponse GetProgram(ProgramService.GetProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgram", ReplyAction="http://tempuri.org/IProgram/GetProgramResponse")]
        System.Threading.Tasks.Task<ProgramService.GetProgramResponse> GetProgramAsync(ProgramService.GetProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgramId", ReplyAction="http://tempuri.org/IProgram/GetProgramIdResponse")]
        ProgramService.GetProgramIdResponse GetProgramId(ProgramService.GetProgramIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgramId", ReplyAction="http://tempuri.org/IProgram/GetProgramIdResponse")]
        System.Threading.Tasks.Task<ProgramService.GetProgramIdResponse> GetProgramIdAsync(ProgramService.GetProgramIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/NewProgram", ReplyAction="http://tempuri.org/IProgram/NewProgramResponse")]
        ProgramService.NewProgramResponse NewProgram(ProgramService.NewProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/NewProgram", ReplyAction="http://tempuri.org/IProgram/NewProgramResponse")]
        System.Threading.Tasks.Task<ProgramService.NewProgramResponse> NewProgramAsync(ProgramService.NewProgramRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgramsXstudent", ReplyAction="http://tempuri.org/IProgram/GetProgramsXstudentResponse")]
        ProgramService.GetProgramsXstudentResponse GetProgramsXstudent(ProgramService.GetProgramsXstudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetProgramsXstudent", ReplyAction="http://tempuri.org/IProgram/GetProgramsXstudentResponse")]
        System.Threading.Tasks.Task<ProgramService.GetProgramsXstudentResponse> GetProgramsXstudentAsync(ProgramService.GetProgramsXstudentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgram", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramRequest
    {
        
        public GetProgramRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgramResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ProgramService.ProgramDTO> GetProgramResult;
        
        public GetProgramResponse()
        {
        }
        
        public GetProgramResponse(System.Collections.Generic.List<ProgramService.ProgramDTO> GetProgramResult)
        {
            this.GetProgramResult = GetProgramResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgramId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long id;
        
        public GetProgramIdRequest()
        {
        }
        
        public GetProgramIdRequest(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgramIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProgramService.ProgramDTO GetProgramIdResult;
        
        public GetProgramIdResponse()
        {
        }
        
        public GetProgramIdResponse(ProgramService.ProgramDTO GetProgramIdResult)
        {
            this.GetProgramIdResult = GetProgramIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewProgram", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewProgramRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProgramService.ProgramRequest Program;
        
        public NewProgramRequest()
        {
        }
        
        public NewProgramRequest(ProgramService.ProgramRequest Program)
        {
            this.Program = Program;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewProgramResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewProgramResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NewProgramResult;
        
        public NewProgramResponse()
        {
        }
        
        public NewProgramResponse(string NewProgramResult)
        {
            this.NewProgramResult = NewProgramResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgramsXstudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramsXstudentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long Id;
        
        public GetProgramsXstudentRequest()
        {
        }
        
        public GetProgramsXstudentRequest(long Id)
        {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProgramsXstudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetProgramsXstudentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ProgramService.ProgramDTO> GetProgramsXstudentResult;
        
        public GetProgramsXstudentResponse()
        {
        }
        
        public GetProgramsXstudentResponse(System.Collections.Generic.List<ProgramService.ProgramDTO> GetProgramsXstudentResult)
        {
            this.GetProgramsXstudentResult = GetProgramsXstudentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IProgramChannel : ProgramService.IProgram, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ProgramClient : System.ServiceModel.ClientBase<ProgramService.IProgram>, ProgramService.IProgram
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProgramClient() : 
                base(ProgramClient.GetDefaultBinding(), ProgramClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProgram.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), ProgramClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ProgramService.GetProgramResponse GetProgram(ProgramService.GetProgramRequest request)
        {
            return base.Channel.GetProgram(request);
        }
        
        public System.Threading.Tasks.Task<ProgramService.GetProgramResponse> GetProgramAsync(ProgramService.GetProgramRequest request)
        {
            return base.Channel.GetProgramAsync(request);
        }
        
        public ProgramService.GetProgramIdResponse GetProgramId(ProgramService.GetProgramIdRequest request)
        {
            return base.Channel.GetProgramId(request);
        }
        
        public System.Threading.Tasks.Task<ProgramService.GetProgramIdResponse> GetProgramIdAsync(ProgramService.GetProgramIdRequest request)
        {
            return base.Channel.GetProgramIdAsync(request);
        }
        
        public ProgramService.NewProgramResponse NewProgram(ProgramService.NewProgramRequest request)
        {
            return base.Channel.NewProgram(request);
        }
        
        public System.Threading.Tasks.Task<ProgramService.NewProgramResponse> NewProgramAsync(ProgramService.NewProgramRequest request)
        {
            return base.Channel.NewProgramAsync(request);
        }
        
        public ProgramService.GetProgramsXstudentResponse GetProgramsXstudent(ProgramService.GetProgramsXstudentRequest request)
        {
            return base.Channel.GetProgramsXstudent(request);
        }
        
        public System.Threading.Tasks.Task<ProgramService.GetProgramsXstudentResponse> GetProgramsXstudentAsync(ProgramService.GetProgramsXstudentRequest request)
        {
            return base.Channel.GetProgramsXstudentAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProgram))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProgram))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50410/Program.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProgramClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProgram);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProgramClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProgram);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProgram,
        }
    }
}
